#    * "0 0 * * * *" = the top of every hour of every day.
#    * "*/10 * * * * *" = every ten seconds.
#    * "0 0 8-10 * * *" = 8, 9 and 10 o'clock of every day.
#    * "0 0 8,10 * * *" = 8 and 10 o'clock of every day.
#    * "0 0/30 8-10 * * *" = 8:00, 8:30, 9:00, 9:30 and 10 o'clock every day.
#    * "0 0 9-17 * * MON-FRI" = on the hour nine-to-five weekdays
#    * "0 0 0 25 12 ?" = every Christmas Day at midnight
#  Cron expression is represented by six fields:
#    second, minute, hour, day of month, month, day(s) of week
util:
  nama-slots:
    calendar-id: i7iji32f77u6341uiv2r1banos@group.calendar.google.com
    chat-id: -1001670736501
    max-check-time: 900000
    cron-expression: 0 */1 5-8,20-22 * * *
  announcements:
    calendar-id: gqhuuojj5287skvo4h4kjlu02s@group.calendar.google.com
    chat-id: -1001670736501
    max-check-time: 900000
    cron-expression: 0 */10 11,12,15,16,20 * * *
  volunteers:
    calendar-id: f2il6u1tibsjgang7iki8m2jv0@group.calendar.google.com
    chat-id: -1001670736501
    max-check-time: 900000
    cron-expression: 0 */10 10,17,18 * * MON-FRI