util:
  nama-slots:
    calendar-id: 9s93iiddq17kr95rumchtmp4mc@group.calendar.google.com
    chat-id: -1001699194736
    schedule-time: 15
    max-check-time: 900000
  announcements:
    calendar-id: n5piq09brtl7646a08s1hojmr8@group.calendar.google.com
    chat-id: -1001699194736
    schedule-time: 30
    max-check-time: 1800000