server:
  port: 9000

util:
  api-token: 5561632586:AAH7dXK2bRVuJoenKZnsstp5b_7VF1k0hCo
  telegram-url: https://api.telegram.org/bot%s/%s
  zoom-url: https://us02web.zoom.us/j/7629526122?pwd=RWo2VmFMRmNzcS9VblF1OEpEUkI0Zz09

service-account:
  json: sa.json
  email: namabhiksha@godcanada-354600.iam.gserviceaccount.com