server:
  port: 9000

util:
  api-token: 5561632586:AAH7dXK2bRVuJoenKZnsstp5b_7VF1k0hCo
  telegram-url: https://api.telegram.org/bot%s/%s
  zoom-url: https://us02web.zoom.us/j/7629526122?pwd=RWo2VmFMRmNzcS9VblF1OEpEUkI0Zz09
  nama-slots:
    calendar-id: 8hddjf9tmq6t707od51ncqiaug@group.calendar.google.com
    chat-id: -1001699194736
    schedule-time: 30
  announcements:
    calendar-id: n5piq09brtl7646a08s1hojmr8@group.calendar.google.com
    chat-id: -1001699194736
    schedule-time: 30

service-account:
  private-key: godcanada-354600-18c327645dec.p12
  email: namabhiksha@godcanada-354600.iam.gserviceaccount.com

