util:
  nama-slots:
    calendar-id: 8hddjf9tmq6t707od51ncqiaug@group.calendar.google.com
    chat-id: -1001699194736
    max-check-time: 1800000
    cron-expression: 0 */15 1-2,4-14,20-22 * * *
  announcements:
    calendar-id: n5piq09brtl7646a08s1hojmr8@group.calendar.google.com
    chat-id: -1001699194736
    max-check-time: 1800000
    cron-expression: 0 */15 11-12,15-16,19-20 * * *
  volunteers:
    calendar-id: atfemsnf6s8pckmfofatkb3vt0@group.calendar.google.com
    chat-id: -1001643817506
    max-check-time: 1800000
    cron-expression: 0 */15 9-10,17-18 * * MON-FRI