name: "Testing EC2 login"
on:
  workflow_dispatch:
  push:
    branches:
      - github_actions

env: 
  AWS_REGION: ca-central-1
  S3BUCKET: nama-bhiksha
  applicationfolder: nbtelegramapp

jobs: 
  build: 
    name: "Build and Package"
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v1
      - name: "Configure AWS credentials"
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          aws-region: "${{ env.AWS_REGION }}"
          aws-secret-access-key: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"

      - name: Get Github action IP
        id: ip
        uses: haythem/public-ip@v1.2 

      - name: Add github actions IP to security group
        env:
          AWS_SECURITY_GROUP: ${{ secrets.AWS_SECURITY_GROUP }}
        run: |
          aws s3 ls
          aws ec2 authorize-security-group-ingress --group-id ${{ env.AWS_SECURITY_GROUP }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/16
          sleep 10

      - name: Deploy on AWS EC2
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY  }}
          HOSTNAME: ${{ secrets.HOSTNAME  }}
          USER_NAME: ${{ secrets.USERNAME  }}
        run: | 
            echo "$PRIVATE_KEY" > private_key.pem && chmod 400 private_key.pem
            ls -al
            echo "trying to logging into EC2..."
            ssh -o StrictHostKeyChecking=no -i private_key.pem ${USER_NAME}@${HOSTNAME}
            # # git clone https://github.com/GOD-Toronto/nbtelegramapp.git
            # cd namabhiksha

            rm -rf private_key.pem
            ls -al



      - name: Run bash script
        run: sh ./.github/scripts/test.sh

      - name: Run online command
        run: |
            echo Folder contents
            ls -al
            rm -rf private_key.pem
            echo "deleted the pem file"
            ls -al


#          ssh -i private_key.pem ${USER_NAME}@${HOSTNAME}
#         hostname
 #         pwd
 #         '
      #  ./.github/scripts/test.sh
          
      #     rm -rf private_key.pem
      # - name: Remove github actions IP from security group
      #   env:
      #     AWS_SECURITY_GROUP: ${{ secrets.AWS_SECURITY_GROUP }}
      #   run: |
      #     aws ec2 revoke-security-group-ingress --group-id ${{ env.AWS_SECURITY_GROUP }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/16
      #   if: always()
