name: "Testing EC2 login"
on:
  workflow_dispatch:
  push:
    branches:
      - github_actions

env: 
  AWS_REGION: ca-central-1
  S3BUCKET: nama-bhiksha
  applicationfolder: nbtelegramapp

jobs: 
  build: 
    name: "Build and Package"
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v1

      - name: Deploy on AWS EC2
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY  }}
          HOSTNAME: ${{ secrets.HOSTNAME  }}
          USER_NAME: ${{ secrets.USERNAME  }}
        run: | 
            echo "$PRIVATE_KEY" > private_key.pem && chmod 600 private_key.pem
            ls -a
            ping -c 4 3.99.135.206
            echo "trying to logging into EC2..."
            # ssh -i private_key.pem ${USER_NAME}@${HOSTNAME}

      - name: Run bash script
        run: sh ./.github/scripts/test.sh

      - name: Run online command
        run: |
            echo Folder contents
            ls -al
            rm -rf private_key.pem
            echo "deleted the pem file"
            ls -al


#          ssh -i private_key.pem ${USER_NAME}@${HOSTNAME}
#         hostname
 #         pwd
 #         '
      #  ./.github/scripts/test.sh
          
      #     rm -rf private_key.pem
      # - name: Remove github actions IP from security group
      #   env:
      #     AWS_SECURITY_GROUP: ${{ secrets.AWS_SECURITY_GROUP }}
      #   run: |
      #     aws ec2 revoke-security-group-ingress --group-id ${{ env.AWS_SECURITY_GROUP }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/16
      #   if: always()
