name: "Build and Deploy"
on:
  workflow_dispatch:
  push:
    branches:
      - github_actions

env: 
  AWS_REGION: ca-central-1
  S3BUCKET: nama-bhiksha
  applicationfolder: nbtelegramapp

jobs: 
  build: 
    name: "Build and Package"
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v1
      - name: "Configure AWS credentials"
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          aws-region: "${{ env.AWS_REGION }}"
          aws-secret-access-key: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
      
      - name: "Set up JDK 17"
        uses: actions/setup-java@v2
        with: 
          cache: gradle
          distribution: adopt
          java-version: 17

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Test with Gradle
        run: ./gradlew clean test

      - name: Build and analyze
        run: ./gradlew build --info

      # - name: "Copy Artifact to superceded s3"    
      #   run: "aws s3 cp s3://${{ env.S3BUCKET }}/nbtelegramapp-0.0.1-SNAPSHOT.jar s3://${{ env.S3BUCKET }}/superceded/"

      # - name: "clear the s3 bucket"
      #   run: aws s3 rm s3://${{ env.S3BUCKET }}/ --recursive  

      - name: "Run pwd bash"
        run: pwd

      - name: "Run ls bash"
        run: ls -al

      # - name: "Copy JAR to S3"
      #   run: aws s3 sync /home/runner/work/nbtelegramapp/nbtelegramapp/build/lib/*.jar s3://nama-bhiksha

      # - name: "Upload Artifact to s3"
      #   run: "aws s3 cp /libs/*.jar s3://${{ env.S3BUCKET }}/"
      #   working-directory: "${{ env.applicationfolder }}/build"

      #C:\Projects\nbtelegramapp\build\libs\nbtelegramapp-0.0.1-SNAPSHOT.jar

      #/home/runner/work/nbtelegramapp/nbtelegramapp/build/lib/nbtelegramapp-0.0.1-SNAPSHOT.jar