on:
  workflow_dispatch:
  push:
    branches:
      - github_actions
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.2
      with:
        switches: -avzr --delete
        path: src/
        remote_path: "/"
        remote_host: ${{ secrets.HOSTNAME }}
        remote_user: ${{ secrets.USERNAME }}
        remote_key: ${{ secrets.SSH_PRIVATE_KEY }}