name: "NamaBhiksha: Build Jar and Deploy"
on:
  workflow_dispatch:
  push:
    branches:
      - github_workflow
jobs: 
  build: 
    name: "Build and Package"
    runs-on: self-hosted

    steps: 
      - uses: actions/checkout@v1

      - name: "Set up JDK 17"
        uses: actions/setup-java@v2
        with: 
          cache: gradle
          distribution: adopt
          java-version: 17

      # - uses: actions/cache@v2
      #   with:
      #     path: |
      #       ~/.gradle/caches
      #       ~/.gradle/wrapper
      #     key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
      #     restore-keys: |
      #       ${{ runner.os }}-gradle-

      - name: Create and move the config file
        env:
          SA_JSON: ${{ secrets.SA_JSON }}
        run: | 
            echo "$SA_JSON" > sa.json 
            mv sa.json ./src/main/resources/config
            cd src//main/resources/config
            ls -al

      - name: Create and move the application-seva yaml  file
        env:
          APPLICATION_SEVA_YAML: ${{ secrets.APPLICATION_SEVA_YAML }}
        run: | 
            echo "$APPLICATION_SEVA_YAML" > application-seva.yml 
            mv application-seva.yml ./src/main/resources
            cd src//main/resources
            ls -al


      # - name: Make gradlew executable
      #   run: chmod +x ./gradlew

      # - name: Test with Gradle
      #   run: ./gradlew clean test

      # - name: Build and analyze
      #   run: ./gradlew build --info

      # - name: Run bash script
      #   run: sh ./.github/scripts/deploy.sh

      # - name: Run online command
      #   run: |
      #       ps -ef|grep java