name: "NamaBhiksha: Build Jar and Deploy"
on:
  workflow_dispatch:
  push:
    branches:
      - github_workflow
jobs: 
  build: 
    name: "Build and Package"
    runs-on: self-hosted

    steps: 
      - uses: actions/checkout@v1

      # - name: "Set up JDK 17"
      #   uses: actions/setup-java@v2
      #   with: 
      #     cache: gradle
      #     distribution: adopt
      #     java-version: 8

      # - name: Create and move the config file
      #   env:
      #     SA_JSON: ${{ secrets.SA_JSON }}
      #   run: | 
      #       cd ./src/main/resources
      #       mkdir config
      #       cd config
      #       echo "$SA_JSON" > sa.json 
      #       pwd
      #       ls -al

      # - name: Create and move the application-seva yaml  file
      #   env:
      #     APPLICATION_SEVA_YAML: ${{ secrets.APPLICATION_SEVA_YAML }}
      #   run: | 
      #       echo "$APPLICATION_SEVA_YAML" > application-seva.yml 
      #       pwd
      #       mv application-seva.yml ./src/main/resources
      #       cd ./src/main/resources
      #       pwd
      #       ls -al

      # - name: Make gradlew executable
      #   run: chmod +x ./gradlew

      # - name: Test with Gradle
      #   run: ./gradlew clean test

      # - name: Build and analyze
      #   run: ./gradlew build --info

      # - name: Cleanup the Nambhiksha folder
      #   run: |
      #       cd /home/ec2-user/namabhiksha
      #       rm *.jar
      #       mv *.log /home/ec2-user/namabhiksha/logs

      # - name: Run bash script
      #   run: sh ./.github/scripts/deploy.sh

      # - name: Run online command
      #   run: |
      #       ps -ef|grep java
      #       echo "cleaning up......."
      #       cd /home/ec2-user/actions-runner/_work/nbtelegramapp/nbtelegramapp
      #       rm -rf *

      - name: Send Build Status email
        if: always()
        uses: dawidd6/action-send-mail@v2
        with:
          # mail server settings
          server_address: smtp.gmail.com
          server_port: 465
          # user credentials
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          # email subject
          subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
          # email body as text
          body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
          # comma-separated string, send email to
          to: balaji.abiraman@gmail.com, uthji2021@gmail.com
          # from email name
          from: Nama Bhiksha GitHub Actions  
